<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>iac</AssemblyName>
    <RootNamespace>Iac.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi.Automation" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Iac.Provisioning\Iac.Provisioning.csproj" />
    <ProjectReference Include="..\Iac.Provisioning.GitHub\Iac.Provisioning.GitHub.csproj" />
    <ProjectReference Include="..\Iac.Provisioning.AzureDevOps\Iac.Provisioning.AzureDevOps.csproj" />
  </ItemGroup>

</Project>
